name: Build, Scan, and Push Docker Image

on:
  workflow_dispatch: 

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t smartaquarius10/kubelogin:latest .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'smartaquarius10/kubelogin:latest'
          format: 'table'
          exit-code: '1'  # Fails pipeline if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Push Docker Image to Docker Hub
        if: success()  # Only push if Trivy scan is successful
        run: |
          docker push smartaquarius10/kubelogin:latest
