name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # 1. NEW: Scan the Dockerfile for bad practices before we even build
      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error #warning 
          
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t smartaquarius10/kubelogin:latest .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: 'smartaquarius10/kubelogin:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'  # Fails pipeline if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Scan for secrets (Trivy)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25  # v0.36.0
        with:
          image-ref: 'smartaquarius10/kubelogin:latest'
          scanners: 'secret'
          exit-code: '1'

      - name: Malware scan (ClamAV - Defense in Depth)
        run: |
          echo "Flattening Docker image for accurate scanning..."
          # Create a dummy container (does not run it)
          CONTAINER_ID=$(docker create smartaquarius10/kubelogin:latest)
          
          # Export the flattened filesystem (exactly as it looks at runtime)
          docker export $CONTAINER_ID -o /tmp/flattened.tar
          docker rm $CONTAINER_ID
          
          # Extract it
          mkdir -p /tmp/unpacked
          # || true prevents the pipeline from failing on harmless symlink warnings during extraction
          tar -xf /tmp/flattened.tar -C /tmp/unpacked || true 
          
          echo "Running ClamAV..."
          # We run freshclam to get today's virus database, then scan the flattened files
          docker run --rm -v /tmp/unpacked:/scan clamav/clamav:latest \
            sh -c "freshclam && clamscan -r --infected --no-summary /scan"
            
      - name: Push Docker Image to Docker Hub
        if: success()  # Only push if Trivy scan is successful
        run: |
          docker push smartaquarius10/kubelogin:latest
